mode: standalone

auth:
  existingSecret: minio-root-credentials
  rootUserSecretKey: root-user
  rootPasswordSecretKey: root-password

defaultBuckets: "postgres-backups"

persistence:
  enabled: true
  storageClass: longhorn-single
  size: 10Gi

service:
  type: ClusterIP
  ports:
    api: 9000

console:
  enabled: false

ingress:
  enabled: false