apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-app.yaml
- secret-superuser.yaml
- secret-backup-creds.yaml
- objectstore.yaml
- cluster.yaml
patches:
- path: secrets-patch.yaml
- path: objectstore-patch.yaml
- path: cluster-patch.yaml
