apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg-main-rw-pooler
  namespace: database
spec:
  cluster:
    name: pg-main
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
      reserve_pool_size: "10"
