apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main-restore-test
  namespace: database
spec:
  storage:
    storageClass: longhorn-ha
  walStorage:
    storageClass: longhorn-ha
