mode: standalone

auth:
  existingSecret: minio-root-credentials
  rootUserSecretKey: root-user
  rootPasswordSecretKey: root-password

defaultBuckets: "postgres-backups"

persistence:
  enabled: true
  storageClass: longhorn
  size: 100Gi

service:
  type: ClusterIP
  ports:
    api: 9000

console:
  service:
    type: ClusterIP
    ports:
      console: 9001

ingress:
  enabled: false

consoleIngress:
  enabled: false