apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 3
  superuserSecret:
    name: superuser-secret
  enableSuperuserAccess: true
  storage:
    storageClass: longhorn-ha
    size: 50Gi
  walStorage:
    storageClass: longhorn-ha
    size: 20Gi
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: app-db-secret
      dataChecksums: true
  monitoring:
    enablePodMonitor: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
