apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: database
stringData:
  password: CHANGE_ME_DEV_APP_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
  namespace: database
stringData:
  password: CHANGE_ME_DEV_SUPERUSER_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-cnpg-creds
  namespace: database
stringData:
  ACCESS_SECRET_KEY: CHANGE_ME_DEV_BACKUP_PASSWORD
