apiVersion: v1
kind: Namespace
metadata:
  name: minio
  annotations:
    field.cattle.io/projectId: local:p-dev-REPLACE
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  annotations:
    field.cattle.io/projectId: local:p-dev-REPLACE
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    field.cattle.io/projectId: local:p-dev-REPLACE
